---
- name: "Downlaod openSCAP Tailring File"
  ansible.builtin.get_url:
    url: https://foreman.moore.corp/pulp/content/bit-devil-orga/Library/custom/bit-devil_product/bit-devil_file_repo/ssg-rhel9-ds-tailoring_20231230.xml
    dest: "/tmp/ssg-rhel9-ds-tailoring_20231230.xml"
    mode: "0440"
    validate_certs: "no"

- name: "Check mit Tailroing File"
  ansible.builtin.shell: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_customized_20231230 --tailoring-file /tmp/ssg-rhel9-ds-tailoring_20231230.xml --results results.xml /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
  ignore_errors: true
























