---
    - name: Check
      ansible.builtin.shell: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis_customized_20231230 --tailoring-file /tmp/ssg-rhel9-ds-tailoring_20231230.xml --results results.xml /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      ignore_errors: true
























