---
- name: "delete old host with same hostname"
  ansible.builtin.shell: |
    curl -k -s -u root:04c7b4aa85227dc8 -H 'Accept: application/json' -X DELETE 'https://localhost:5665/v1/objects/hosts/{{ vm_name_fqdn }}?cascade=1'

- name: set downtime to host
  ansible.builtin.uri:
    url: https://localhost:5665/v1/objects/hosts/{{ vm_name_fqdn }}
    user: <api user>
    password: <PW>
    validate_certs: false
    method: PUT
    body_format: json
    headers:
      Accept: "application/json"
    status_code: 200
    body: 
       '{"templates": [ "{{ icinga_check_template }}" ],"attrs": { "address": "{{ ip_address }}", "vars.os" : "{{ icinga_check_template }}", "vars.host_ssh_native" : "{{ ip_address }}" }}'
